Bubble sort
allun26/Bubble-sort pull request #1
Opened 2019-08-08 22:27 UTC by rociac

Hello, looking forward to your feedback!

2019-08-08 22:48 UTC, rociac commented
We fixed some spacing errors on the linter but we don't know if we should change the others, looking forward for your feedback!

2019-08-09 01:01 UTC, AdnanAfsari commented
### **ADNAN AFSARI WORKING ON IT**

2019-08-09 01:28 UTC, AdnanAfsari requested changes
Hello @allun26 @Frodoosk 

Project looks good so far but you have to fix those linter errors. there are two errors that i commented i am also not sure in this project. i will let you know in your future review.
but fix other errors and submit for another review.

you can check this repo if you need any help with linter 
https://github.com/microverseinc/linters-config#linters-config

Happy Coding

2019-08-09 01:28 UTC, AdnanAfsari commented on ruby.rb
> +    for i in 0...array.length - 1
let me ask seniors about this kind of errors in this project.

2019-08-09 01:28 UTC, AdnanAfsari commented on ruby.rb
> +    for i in 0...array.length - 1
let me ask seniors about this kind of errors in this project.

2019-08-09 19:21 UTC, mosaaleb requested changes
## Nice job @allun26 , @Frodoosk 
The logic is right and the test case have passed. Still the same errors marked by my fellow TSE appear in the checks.

**`Prefer each over for.`**
We can solve it two ways:
- `array[0..-2].each.with_index do |_, i|`
  
  - Note that we excluded that last element with `[0..-2]` because `array[i + 1]` will give error at the last loop iteration.
  - The `_` in the `|_, i|` because the element will not be used inside the array so that way we ignore it. Here's a link from [ruby style guidelines](https://github.com/rubocop-hq/ruby-style-guide#trailing-underscore-variables).

- `(array.length - 1).times do |i|` This also won't give errors

Please fix these minor issues and submit a new code review.

### Happy Coding :computer:

2019-08-12 16:01 UTC, mosaaleb commented
### Congratulations @allun26 @Frodoosk :clap:

You can merge into master :+1: 

Good luck with the next projects.

## Happy Coding :computer:

2019-08-12 16:02 UTC, mosaaleb approved these changes
### Congratulations @allun26 @Frodoosk :clap:

You can merge into master :+1: 

Good luck with the next projects.

## Happy Coding :computer:

2019-08-12 19:03 UTC, merged